name: Setup
description: Common setup steps for workflows

inputs:
  dependencies-command:
    description: Command to install dependencies
    required: false
    default: 'uv sync --frozen'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install dependencies
      run: ${{ inputs.dependencies-command }}
      shell: bash

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Create .env file from example
      run: cp .env.example .env
      shell: bash