name: Run Local Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: ./.uv-cache
    strategy:
      matrix:
        test_target: [unit-test, sdk-test, intg-test]
      fail-fast: false

    steps:
      - uses: ./.github/actions/setup

      - name: Run tests
        run: |
          just ${{ matrix.test_target }}