name: Run Linters

on:
  workflow_call:

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
        with:
          dependencies-command: 'uv sync --only-group dev --frozen'

      - name: Run Linters
        run: just lint
